[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Hedgehog = "7f16798b-0e18-40de-98af-932948254698"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
KittyTerminalImages = "b7fa5abe-5c7d-46c6-a1ae-1026d0d509b9"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Lasso = "b4fcebef-c861-5a0f-a7e2-ba9dc32b180a"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
PlotThemes = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RData = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
